/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CannotAccessUserRouteImport } from './routes/cannot-access-user'
import { Route as CanAccessOnlyUserRouteImport } from './routes/can-access-only-user'
import { Route as CanAccessAnyoneRouteImport } from './routes/can-access-anyone'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CannotAccessUserRoute = CannotAccessUserRouteImport.update({
  id: '/cannot-access-user',
  path: '/cannot-access-user',
  getParentRoute: () => rootRouteImport,
} as any)
const CanAccessOnlyUserRoute = CanAccessOnlyUserRouteImport.update({
  id: '/can-access-only-user',
  path: '/can-access-only-user',
  getParentRoute: () => rootRouteImport,
} as any)
const CanAccessAnyoneRoute = CanAccessAnyoneRouteImport.update({
  id: '/can-access-anyone',
  path: '/can-access-anyone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/can-access-anyone': typeof CanAccessAnyoneRoute
  '/can-access-only-user': typeof CanAccessOnlyUserRoute
  '/cannot-access-user': typeof CannotAccessUserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/can-access-anyone': typeof CanAccessAnyoneRoute
  '/can-access-only-user': typeof CanAccessOnlyUserRoute
  '/cannot-access-user': typeof CannotAccessUserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/can-access-anyone': typeof CanAccessAnyoneRoute
  '/can-access-only-user': typeof CanAccessOnlyUserRoute
  '/cannot-access-user': typeof CannotAccessUserRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/can-access-anyone'
    | '/can-access-only-user'
    | '/cannot-access-user'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/can-access-anyone'
    | '/can-access-only-user'
    | '/cannot-access-user'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/can-access-anyone'
    | '/can-access-only-user'
    | '/cannot-access-user'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanAccessAnyoneRoute: typeof CanAccessAnyoneRoute
  CanAccessOnlyUserRoute: typeof CanAccessOnlyUserRoute
  CannotAccessUserRoute: typeof CannotAccessUserRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cannot-access-user': {
      id: '/cannot-access-user'
      path: '/cannot-access-user'
      fullPath: '/cannot-access-user'
      preLoaderRoute: typeof CannotAccessUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/can-access-only-user': {
      id: '/can-access-only-user'
      path: '/can-access-only-user'
      fullPath: '/can-access-only-user'
      preLoaderRoute: typeof CanAccessOnlyUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/can-access-anyone': {
      id: '/can-access-anyone'
      path: '/can-access-anyone'
      fullPath: '/can-access-anyone'
      preLoaderRoute: typeof CanAccessAnyoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanAccessAnyoneRoute: CanAccessAnyoneRoute,
  CanAccessOnlyUserRoute: CanAccessOnlyUserRoute,
  CannotAccessUserRoute: CannotAccessUserRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
