/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GroupListRouteImport } from './routes/group-list'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsetListRouteImport } from './routes/cardset-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UserUserIdIndexRouteImport } from './routes/user/$userId/index'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as CardsetsLearningIndexRouteImport } from './routes/cardsets/learning/index'
import { Route as GroupsGroupIdManageRouteImport } from './routes/groups/$groupId/manage'
import { Route as CardsetsEditorIdRouteImport } from './routes/cardsets/editor/$id'
import { Route as GroupsGroupIdCardsetsCardsetIdIndexRouteImport } from './routes/groups/$groupId/cardsets/$cardsetId/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupListRoute = GroupListRouteImport.update({
  id: '/group-list',
  path: '/group-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetListRoute = CardsetListRouteImport.update({
  id: '/cardset-list',
  path: '/cardset-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdIndexRoute = UserUserIdIndexRouteImport.update({
  id: '/user/$userId/',
  path: '/user/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetsLearningIndexRoute = CardsetsLearningIndexRouteImport.update({
  id: '/cardsets/learning/',
  path: '/cardsets/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdManageRoute = GroupsGroupIdManageRouteImport.update({
  id: '/groups/$groupId/manage',
  path: '/groups/$groupId/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetsEditorIdRoute = CardsetsEditorIdRouteImport.update({
  id: '/cardsets/editor/$id',
  path: '/cardsets/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdCardsetsCardsetIdIndexRoute =
  GroupsGroupIdCardsetsCardsetIdIndexRouteImport.update({
    id: '/groups/$groupId/cardsets/$cardsetId/',
    path: '/groups/$groupId/cardsets/$cardsetId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardset-list': typeof CardsetListRoute
  '/dashboard': typeof DashboardRoute
  '/group-list': typeof GroupListRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/cardsets/editor/$id': typeof CardsetsEditorIdRoute
  '/groups/$groupId/manage': typeof GroupsGroupIdManageRoute
  '/cardsets/learning': typeof CardsetsLearningIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/user/$userId': typeof UserUserIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId': typeof GroupsGroupIdCardsetsCardsetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardset-list': typeof CardsetListRoute
  '/dashboard': typeof DashboardRoute
  '/group-list': typeof GroupListRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/cardsets/editor/$id': typeof CardsetsEditorIdRoute
  '/groups/$groupId/manage': typeof GroupsGroupIdManageRoute
  '/cardsets/learning': typeof CardsetsLearningIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/user/$userId': typeof UserUserIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId': typeof GroupsGroupIdCardsetsCardsetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardset-list': typeof CardsetListRoute
  '/dashboard': typeof DashboardRoute
  '/group-list': typeof GroupListRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/': typeof GroupsIndexRoute
  '/cardsets/editor/$id': typeof CardsetsEditorIdRoute
  '/groups/$groupId/manage': typeof GroupsGroupIdManageRoute
  '/cardsets/learning/': typeof CardsetsLearningIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId/': typeof GroupsGroupIdCardsetsCardsetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardset-list'
    | '/dashboard'
    | '/group-list'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/groups/create'
    | '/groups'
    | '/cardsets/editor/$id'
    | '/groups/$groupId/manage'
    | '/cardsets/learning'
    | '/groups/$groupId'
    | '/user/$userId'
    | '/groups/$groupId/cardsets/$cardsetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardset-list'
    | '/dashboard'
    | '/group-list'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/groups/create'
    | '/groups'
    | '/cardsets/editor/$id'
    | '/groups/$groupId/manage'
    | '/cardsets/learning'
    | '/groups/$groupId'
    | '/user/$userId'
    | '/groups/$groupId/cardsets/$cardsetId'
  id:
    | '__root__'
    | '/'
    | '/cardset-list'
    | '/dashboard'
    | '/group-list'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/groups/create'
    | '/groups/'
    | '/cardsets/editor/$id'
    | '/groups/$groupId/manage'
    | '/cardsets/learning/'
    | '/groups/$groupId/'
    | '/user/$userId/'
    | '/groups/$groupId/cardsets/$cardsetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsetListRoute: typeof CardsetListRoute
  DashboardRoute: typeof DashboardRoute
  GroupListRoute: typeof GroupListRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  CardsetsEditorIdRoute: typeof CardsetsEditorIdRoute
  GroupsGroupIdManageRoute: typeof GroupsGroupIdManageRoute
  CardsetsLearningIndexRoute: typeof CardsetsLearningIndexRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  UserUserIdIndexRoute: typeof UserUserIdIndexRoute
  GroupsGroupIdCardsetsCardsetIdIndexRoute: typeof GroupsGroupIdCardsetsCardsetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-list': {
      id: '/group-list'
      path: '/group-list'
      fullPath: '/group-list'
      preLoaderRoute: typeof GroupListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardset-list': {
      id: '/cardset-list'
      path: '/cardset-list'
      fullPath: '/cardset-list'
      preLoaderRoute: typeof CardsetListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/': {
      id: '/user/$userId/'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardsets/learning/': {
      id: '/cardsets/learning/'
      path: '/cardsets/learning'
      fullPath: '/cardsets/learning'
      preLoaderRoute: typeof CardsetsLearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/manage': {
      id: '/groups/$groupId/manage'
      path: '/groups/$groupId/manage'
      fullPath: '/groups/$groupId/manage'
      preLoaderRoute: typeof GroupsGroupIdManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardsets/editor/$id': {
      id: '/cardsets/editor/$id'
      path: '/cardsets/editor/$id'
      fullPath: '/cardsets/editor/$id'
      preLoaderRoute: typeof CardsetsEditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/cardsets/$cardsetId/': {
      id: '/groups/$groupId/cardsets/$cardsetId/'
      path: '/groups/$groupId/cardsets/$cardsetId'
      fullPath: '/groups/$groupId/cardsets/$cardsetId'
      preLoaderRoute: typeof GroupsGroupIdCardsetsCardsetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsetListRoute: CardsetListRoute,
  DashboardRoute: DashboardRoute,
  GroupListRoute: GroupListRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  CardsetsEditorIdRoute: CardsetsEditorIdRoute,
  GroupsGroupIdManageRoute: GroupsGroupIdManageRoute,
  CardsetsLearningIndexRoute: CardsetsLearningIndexRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  UserUserIdIndexRoute: UserUserIdIndexRoute,
  GroupsGroupIdCardsetsCardsetIdIndexRoute:
    GroupsGroupIdCardsetsCardsetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
