/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as CardsetsEditorRouteImport } from './routes/cardsets/editor'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdCardsetsCardsetIdRouteImport } from './routes/groups/$groupId/cardsets/$cardsetId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsetsEditorRoute = CardsetsEditorRouteImport.update({
  id: '/cardsets/editor',
  path: '/cardsets/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdCardsetsCardsetIdRoute =
  GroupsGroupIdCardsetsCardsetIdRouteImport.update({
    id: '/groups/$groupId/cardsets/$cardsetId',
    path: '/groups/$groupId/cardsets/$cardsetId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cardsets/editor': typeof CardsetsEditorRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId': typeof GroupsGroupIdCardsetsCardsetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cardsets/editor': typeof CardsetsEditorRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId': typeof GroupsGroupIdCardsetsCardsetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/cardsets/editor': typeof CardsetsEditorRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/cardsets/$cardsetId': typeof GroupsGroupIdCardsetsCardsetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/cardsets/editor'
    | '/groups/create'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/cardsets/$cardsetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/cardsets/editor'
    | '/groups/create'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/cardsets/$cardsetId'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/auth/login'
    | '/auth/register'
    | '/cardsets/editor'
    | '/groups/create'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/cardsets/$cardsetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CardsetsEditorRoute: typeof CardsetsEditorRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdCardsetsCardsetIdRoute: typeof GroupsGroupIdCardsetsCardsetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardsets/editor': {
      id: '/cardsets/editor'
      path: '/cardsets/editor'
      fullPath: '/cardsets/editor'
      preLoaderRoute: typeof CardsetsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/cardsets/$cardsetId': {
      id: '/groups/$groupId/cardsets/$cardsetId'
      path: '/groups/$groupId/cardsets/$cardsetId'
      fullPath: '/groups/$groupId/cardsets/$cardsetId'
      preLoaderRoute: typeof GroupsGroupIdCardsetsCardsetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CardsetsEditorRoute: CardsetsEditorRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdCardsetsCardsetIdRoute: GroupsGroupIdCardsetsCardsetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
